# Generated by Django 5.1.4 on 2024-12-20 03:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='long_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
