# Generated by Django 5.1.4 on 2024-12-22 14:42

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_long_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=products.models.generate_unique_image_name),
        ),
    ]
